
server:
  port: 8091

spring:
  boot:
    admin:
      client:
        url: http://localhost:8083/
        
        
        
        
  datasource:
     username: root
     password: mahadev7041
     url: jdbc:mysql://localhost:3306/his_dev_db
     driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true 

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
